Table olist_customers_dataset {
  customer_id string [pk]
  customer_unique_id string
  customer_zip_code_prefix int
  customer_city string
  customer_state string
}

Table olist_geolocation_dataset {
  geolocation_zip_code_prefix int
  geolocation_lat float
  geolocation_lng float
  geolocation_city string
  geolocation_state string
}

Table olist_order_items_dataset {
  order_id string
  order_item_id int
  product_id string
  seller_id string
  shipping_limit_date datetime
  price float
  freight_value float
  indexes {
    (order_id, order_item_id) [pk]
  }
}

Table olist_order_payments_dataset {
  order_id string
  payment_sequential int
  payment_type string
  payment_installments int
  payment_value float
  indexes {
    (order_id, payment_sequential) [pk]
  }
}

Table olist_order_reviews_dataset {
  review_id string
  order_id string
  review_score int
  review_comment_title string
  review_comment_message string
  review_creation_date datetime
  review_answer_timestamp datetime
  indexes {
    (review_id, order_id) [pk]
  }
}

Table olist_orders_dataset {
  order_id string [pk]
  customer_id string
  order_status string
  order_purchase_timestamp datetime
  order_approved_at string
  order_delivered_carrier_date datetime
  order_delivered_customer_date datetime
  order_estimated_delivery_date datetime
}

Table olist_products_dataset {
  product_id string [pk]
  product_category_name string
  product_name_lenght float
  product_description_lenght float
  product_photos_qty float
  product_weight_g float
  product_length_cm float
  product_height_cm float
  product_width_cm float
}

Table olist_sellers_dataset {
  seller_id string [pk]
  seller_zip_code_prefix int
  seller_city string
  seller_state string
}

Table product_category_name_translation {
  product_category_name string [pk]
  product_category_name_english string
}

Ref: olist_customers_dataset.customer_id > olist_orders_dataset.customer_id  // 1:1
Ref: olist_order_items_dataset.order_id > olist_orders_dataset.order_id  // 1:N
Ref: olist_order_items_dataset.product_id > olist_products_dataset.product_id  // 1:N
Ref: olist_order_items_dataset.seller_id > olist_sellers_dataset.seller_id  // 1:N
Ref: olist_order_payments_dataset.order_id > olist_orders_dataset.order_id  // 1:N
Ref: olist_order_reviews_dataset.order_id > olist_orders_dataset.order_id  // 1:N
Ref: olist_products_dataset.product_category_name > product_category_name_translation.product_category_name  // 1:N